### ISSUE TITLE
UI.cover 全屏浮层 的问题

### ISSUE THREAD

**Issue by robinma** [bh-lay/UI#1]
刚做了个demo，发现打开浮层后，还可以滚动，并具浮层也跟着跑了，这个定位应该设置成fixed，你说呢.
还有就是烦请出一个简化版的，以专用于移动或高级浏览器。

还有关于UI样式问题，这要自己用时，把UI改了，再自己打包，是否？

**Comment by bh-lay** [comment]
需求里提到的几点（fixed、简化版、UI），与目前所写有所出入，欢迎fork项目，修改之，个人精力有限，感激不尽！
