### ISSUE TITLE
关于自定义对话框组件实现的一些疑惑

### ISSUE THREAD

**Issue by xyeric** [bh-lay/UI#2]
看了[demo页面](http://bh-lay.com/demo/lab/UI/demo.html)，对话框做得很棒哈~。
之前有过类似的尝试，就是使用自定义的组件去替换浏览器内置的alert模态框，但是在实际应用中出现过很多问题，同时在这个实现中也发现几点不明的地方想请教一下，简单罗列如下：
1. demo页面，【弹框】列表的第一个项来说，当"纯内容"那一条获取焦点之后，多次回车会重复弹出多个对话框。
2.demo页面，弹框显示以后，不支持回车关闭
3.自定义的弹窗不能阻塞后面js代码的运行，如何保障代码的运行时序。

**Comment by bh-lay** [comment]
灰常感谢赞赏，也分常感谢这么细致的提问，这里我简单对问题做下回答，仅供参考。

1、这里的对话框，仅仅作为对话框自身的实现，不理会调用者的逻辑，是否同时显示多个对话框这个属于调用者的控制范围，弹框本身不去干预。也就是说，在这里提到的a链接的事件中可以做到控制是否只显示一个对话框（弹框兑现有关闭事件，可以用来控制窗口是否已被关闭）；
2、在有确认信息（confirm）字段的弹出框，确实有必要增加回车、esc关闭、取消逻辑，但一直未理清如何剥离按键与页面事件的分离（弹框本身没有keydown事件），避免不必要的BUG，这一块也是我接下来要做的东西；
3、原生的alert、confirm皆为同步阻塞式，而所有的模拟实现，皆为异步的，在这类弹窗中，可以用confirm参数来的回调来执行选择后要执行的任务。
