### ISSUE TITLE
UI.pop的param.html含有input[type=radio]的时候

### ISSUE THREAD

**Issue by shynee** [bh-lay/UI#3]
html = [input type=radio name=xx checked=checked] +
[input type=radio name=xx ];
UI.pop({
'mask' : true,
'title' : 'test',
'width' : 500,
'easyClose' : false,
'html' : html
})
pop打开的时候会取消掉input的选择

**Comment by shynee** [comment]
[input type=radio name=xx checked=checked]
[input type=radio name=xx ]
不好意思，忘记尖括号会被吃了

**Comment by bh-lay** [comment]
我用了本机的两个浏览器测试，没有重现问题，重现所用的代码如下。

Win7 32位 Chrome 42
Win7 32位 IE 9

```
UI.pop({
  'mask' : true,
  'title' : 'test',
  'width' : 500,
  'easyClose' : false,
  'html' : 'A:<input type=radio name=xx checked=checked>  B:<input type=radio name=xx>'
})
```

麻烦检查我所用的代码和你的是否一致，可以的话提供下你所用的系统及浏览器，我再测试一下，非常感谢！

**Comment by bh-lay** [comment]
新版本已解决此issue，我实现能不能关掉这个issue！
