### ISSUE TITLE
选择组件在页面滚动或改变大小后自动居中

### ISSUE THREAD

**Issue by woodensail** [bh-lay/UI#5]
这个保持居中功能似乎是所有组件通用的？但是demo中select本身点击后不是居中的，所以滚动或改变大小后变为居中就会感觉很奇怪。

**Comment by bh-lay** [comment]
了解，加入工期，今晚搞定，3Q ！

**Comment by bh-lay** [comment]
问题已于昨晚修复，非常感谢反馈！
见commit: 3790b142dc94f9d6bcd2fef1d24b4864fa3832db
